"""
Code related to BIDS datasets.
"""
# from __future__ import annotations

from pathlib import Path, PosixPath
from typing import Optional, Any, List
import json

from pydantic import BaseModel, DirectoryPath, FilePath, Field, field_validator
from bids import BIDSLayout

class GeneratedBy(BaseModel):
    Name: str = Field(title="Name", description="Name of the software used to generate the dataset")
    Version: Optional[str] = Field(title="Version", description="Version of the software used to generate the dataset")
    Description: Optional[str] = Field(title="Description", description="Description of the software used to generate the dataset")
    CodeURL: Optional[str] = Field(title="Code URL", description="URL to the code used to generate the dataset")
    Container: Optional[dict[str, str]] = Field(title="Container", description="Container information", default={})

class DatasetDescription(BaseModel):
    """
    Dataset description.
    """
    Name: str = Field(title="Name", description="Name of the dataset")
    BIDSVersion: str = Field(title="BIDS version", description="BIDS version", default="0.0.0")
    HEDVersion: Optional[str | list[str]] = Field(title="HED version", description="HED version", default="")
    DatasetLinks: Optional[str] = Field(title="Dataset links", description="Links to the dataset", default="")
    DatasetType: Optional[str] = Field(title="Dataset type", description="Type of the dataset", default="raw")
    License: Optional[str] = Field(title="License", description="License information", default="CC0")
    Authors: Optional[list[str]] = Field(title="Authors", description="Authors", default=[])
    Acknowledgements: Optional[str] = Field(title="Acknowledgements", description="Acknowledgements", default="")
    HowToAcknowledge: Optional[str] = Field(title="How to acknowledge", description="How to acknowledge the dataset", default="")
    Funding: Optional[list[str]] = Field(title="Funding", description="Funding information", default=[])
    EthicsApprovals: Optional[list[str]] = Field(title="Ethics approvals", description="Ethics approvals", default=[])
    ReferencesAndLinks: Optional[list[str]] = Field(title="References and links", description="References and links", default=[])
    DatasetDOI: Optional[str] = Field(title="Dataset DOI", description="Dataset DOI", default="")
    GeneratedBy: Optional[list[Any]] = Field(title="Generated by", description="Generated by.", default=[
        GeneratedBy(Name="BIDS Pipeline", Version="0.0.1", Description="BIDS Pipeline", CodeURL="")
    ])
    SourceDatasets: Optional[list[dict[str, str]]] = Field(title="Source datasets", description="Source datasets", default=[])
    
    @field_validator("GeneratedBy", mode="before")
    def set_GeneratedBy(cls, v):
        if isinstance(v, dict):
            return [GeneratedBy(**v)]
        elif isinstance(v, list):
            return [GeneratedBy(**item) for item in v]
        return v
    
    @classmethod
    def from_file(cls, path: str) -> "DatasetDescription":
        """
        Load dataset description from a JSON file.
        """
        with open(path, "r") as f:
            data: dict = json.load(f)
        return cls(**data)
    
def update_participants_json(participants_dict: Optional[dict], overwrite: bool = False, **kwargs) -> dict[str, Any]:
    """
    Add/update participants.json information.
    """
    default_participants_dict: dict[str, Any] = {
        "age": {
            "Description": "age of the participant",
            "Units": "year"
        },
        "sex": {
            "Description": "sex of the participant as reported by the participant",
            "Levels": {
                "M": "male",
                "F": "female"
            }
        },
        "handedness": {
            "Description": "handedness of the participant as reported by the participant",
            "Levels": {
                "left": "left",
                "right": "right"
            }
        },
        "group": {
            "Description": "experimental group the participant belonged to",
            "Levels": {
                "read": "participants who read an inspirational text before the experiment",
                "write": "participants who wrote an inspirational text before the experiment"
            }
        }
    }
    if participants_dict is None:
        participants_dict = default_participants_dict
    
    for key, value in kwargs.items():
        if overwrite or key not in participants_dict:
            participants_dict[key] = value
    return participants_dict